### ISSUE TITLE
O site de consulta não é acessível via browser mesmo?

### ISSUE THREAD

**Issue by tramontini** [turicas/cursos-prouni#1]
O site de consulta não é acessível via browser ou tiraram o link do ar? 
Será que também não teria algum lugar de onde pudesse ser extraída a informação da renda de quem utiliza o prouni, sexo, raça e etc..? Mesmo que não fale quem é a pessoa?
Ai poderia cruzar curso x quem usa para ver se o uso está sendo feito por quem realmente precisa

**Comment by turicas** [comment]
Esse site costuma sair do ar poucos dias depois de fechar a inscrição.
Talvez no [site do INEP](http://portal.inep.gov.br/microdados) você consiga pegar informações do censo da educação superior (essas informações que você quer devem estar provavelmente nos microdados).
